server:
  port: ${SERVER_PORT:62558}

skynet:
  chain-length: 10
  pattern-length: 20
  min-chunk-size: 5
  max-chunk-size: 5

spring:
  jpa:
    database: h2
    show-sql: true
  datasource:
    initialization-mode: embedded
    platform: h2
